E10 1/solicitar transporte
djonathanb/unipar-2021-trabalho-plano pull request #16
Opened 2021-11-27 20:37 UTC by lucasbaccan

- Alterado estrutura de endereço
- E10.1 - Solicitação de transporte

Exemplo de request para criar uma solicitação de trasnporte:
```
curl --location --request POST 'localhost:8080/transportes' \
--header 'Content-Type: application/json' \
--data-raw '{
    "carteirinha": {
        "id": {
            "id": "189cd88d-dc08-41a1-9e9d-6abc82390398"
        }
    },
    "enderecoOrigem": {
        "cep": "1",
        "bairro": "2",
        "logradouro": "3",
        "complemento": "4"
    },
    "enderecoDestino": {
        "cep": "4",
        "bairro": "3",
        "logradouro": "2",
        "complemento": "1"
    },
    "tipoTransporte": "AEREO"
}'
```

2021-11-28 14:28 UTC, BrunoSzczuk requested changes
Muito bom!
Adicionei alguns pontos de melhoria.
Senti falta dos testes da camada de Resource também.

2021-11-28 14:28 UTC, BrunoSzczuk commented on src/main/kotlin/br/unipar/plano/domain/transportes/services/impl/TransporteQueryServiceImpl.kt
> +        Exception("Transporte com id ${idTransporte.id} não encontrada")
Utilizar a exceção já criada para casos de "NotFound"

2021-11-28 14:28 UTC, BrunoSzczuk commented on src/main/kotlin/br/unipar/plano/interfaces/rest/transportes/TransporteDTO.kt
> +    val carteirinha: Carteirinha,
Utilizar classe DTO ao invés da classe de domínio

2021-11-28 14:28 UTC, BrunoSzczuk commented on src/main/kotlin/br/unipar/plano/interfaces/rest/transportes/TransporteDTO.kt
> +    @field:Size(min = 1010000)
Adicionar mensagem para avisar o usuário sobre a exceção

2021-11-28 14:28 UTC, BrunoSzczuk commented on src/main/kotlin/br/unipar/plano/domain/transportes/model/Transporte.kt
> +            throw Exception("Não é possível cancelar um Transporte com status $status")
Utilizar outra classe de exceção, ou ainda, criar uma para este caso.

2021-11-28 14:28 UTC, BrunoSzczuk commented on src/main/kotlin/br/unipar/plano/domain/transportes/model/Transporte.kt
> +            throw Exception("Não é possível aprovar um Transporte com status $status")
Utilizar outra classe de exceção, ou ainda, criar uma para este caso.

2021-11-28 16:50 UTC, lucasbaccan commented on src/main/kotlin/br/unipar/plano/domain/transportes/services/impl/TransporteQueryServiceImpl.kt
> +        Exception("Transporte com id ${idTransporte.id} não encontrada")
Tinha me baseado na versão da semana passada da aula, vi agora que o professor alterou

2021-11-28 16:52 UTC, lucasbaccan commented on src/main/kotlin/br/unipar/plano/domain/transportes/model/Transporte.kt
> +            throw Exception("Não é possível cancelar um Transporte com status $status")
Tinha me baseado na versão da semana passada da aula, vi agora que o professor alterou

2021-11-28 17:13 UTC, lucasbaccan commented on src/main/kotlin/br/unipar/plano/interfaces/rest/transportes/TransporteDTO.kt
> +    val carteirinha: Carteirinha,
Verdade, nem me toquei.
Alterei aqui já.

2021-11-29 02:20 UTC, lucasbaccan commented
Migrado PR para https://github.com/djonathanb/unipar-2021-trabalho-plano/pull/22 que contem tudo da equipe E10

2021-11-29 02:20 UTC, closed without merging