E2 1/cadastro plano
djonathanb/unipar-2021-trabalho-plano pull request #19
Opened 2021-11-28 21:36 UTC by sergioschu

Falta a validação para não permitir excluir plano que está vinculado a um contrato, pois será implementado assim que ser possível usar os endpoints dos colegas referente a contratos.

2021-11-28 23:35 UTC, Lucas-Martins-de-Oliveira approved these changes

2021-11-29 00:17 UTC, BrunoSzczuk approved these changes
Parabéns pela entrega!
Deixei alguns pontos pequenos pra ajustes, já vou deixar aprovado.

2021-11-29 00:17 UTC, BrunoSzczuk commented on src/main/kotlin/br/unipar/plano/interfaces/rest/planos/PlanoDTO.kt
> +    val valorbase: Double,
Texto da mensagem incorreto

2021-11-29 00:17 UTC, BrunoSzczuk commented on src/main/kotlin/br/unipar/plano/interfaces/rest/planos/PlanoResource.kt
> +    }
Faltando documentação dos retornos HTTPs

2021-12-01 02:54 UTC, djonathanb requested changes

2021-12-01 02:54 UTC, djonathanb commented on src/main/kotlin/br/unipar/plano/domain/planos/model/Plano.kt
> +        val transporteaereo: Boolean = false,
```suggestion
        val transporteAereo: Boolean = false,
```

2021-12-01 02:54 UTC, djonathanb commented on src/main/kotlin/br/unipar/plano/domain/planos/model/Plano.kt
> +        val valorbase: Double = 100.0,
```suggestion
        val valorBase: BigDecimal = BigDecimal.valueOf(100.0),
```

2021-12-01 02:54 UTC, djonathanb commented on src/test/kotlin/br/unipar/plano/domain/planos/model/factories/planoTestConsts.kt
> +val PLANO_CO_ID = IdPlano(UUID.fromString("4a2fadf0-4f59-4a2e-b310-a2b264e9e88a"))
Quando eu utilizei a sigla _CO_ nas minhas constantes de teste eu me referia ao nome da central (Costa Oeste), no caso do plano vocês podem utilizar algo diferente como `PLANO_CCMA_50_ID`.

2021-12-01 04:39 UTC, evertonab commented
> Falta a validação para não permitir excluir plano que está vinculado a um contrato, pois será implementado assim que ser possível usar os endpoints dos colegas referente a contratos.

Commit com o código implementado:
https://github.com/djonathanb/unipar-2021-trabalho-plano/commit/aca83da8cc5a1add2f35bc8dd0162c6609d7c3d4

2021-12-03 12:16 UTC, sergioschu commented on src/main/kotlin/br/unipar/plano/interfaces/rest/planos/PlanoResource.kt
> +    }
Que documentação se refere? tem algum modelo?

2021-12-05 02:10 UTC, djonathanb approved these changes

2021-12-05 02:25 UTC, djonathanb commented
@Lucas-Martins-de-Oliveira me envie o relatório no email, por favor

2021-12-06 12:57 UTC, merged